//Defines for helm command types
#define HELM_IDLE 0
#define HELM_FULL_STOP 1
#define HELM_MOVE_TO_DESTINATION 2
#define HELM_TURN_TO_DESTINATION 3
#define HELM_FOLLOW_SENSOR_LOCK 4
#define HELM_TURN_TO_SENSOR_LOCK 5

#define SHUTTLE_TAB_GENERAL 0
#define SHUTTLE_TAB_ENGINES 1
#define SHUTTLE_TAB_HELM 2
#define SHUTTLE_TAB_SENSORS 3
#define SHUTTLE_TAB_TARGET 4
#define SHUTTLE_TAB_DOCKING 5
